### PR TITLE
Feature/return key for uploaded file in params

### PR DESCRIPTION
**Pull request by Ryan-Knowles**
# what

- When s3 direct files are uploaded, the s3direct library will generate a key that is then passed back via the get_upload_params view response
- The key is then added to the videoUploadForm's key input field

# why

- This allows the key to be passed back to the vocalized app via the create video view, and used when creating a video

# references

This satisfies the s3 direct portion of this ticket:
- Asana Ticket: https://app.asana.com/0/1188034199927926/1200009335116847

### CODE REVIEW

**Comment by Ryan-Knowles** [comment]
@semanticmx Please review

**Review by semanticmx — APPROVED** [review]
looks good

**Comment by semanticmx** [comment]
@Ryan-Knowles are you using a JS linter now?

**Comment by Ryan-Knowles** [comment]
@semanticmx I am running the tests associated with the project but I think it is just python quality checking

**Pull request merged**
